#!/bin/sh -e

PATH=$PWD/..:$PATH

find . -mindepth 1 -maxdepth 1 -type d | while read test; do
    echo "$test..."
    (cd "$test" && changelogfmt < input.md) | git diff --no-index - "$test/expected.md"

    # Also test expected against itself to ensure consistency.
    (cd "$test" && changelogfmt < expected.md) | git diff --no-index - "$test/expected.md"
done
